config:
  BIND_PORT: 8086
  BIND_ADDRESS: 127.0.0.1
  APP_BASE_URL: http://127.0.0.1:8086
  API_BASE_URL: http://127.0.0.1:8086/api
  WEB_PUBLIC_ROOT: ./_webroot
  DB_PATH: ./db/MyKoa.db
  SESSION_SECRET: REGENERATE_SESSION_SECRET
  SSL:
    ENABLED: false
    KEY_PATH: .secrets/key.pem
    CERT_PATH: .secrets/cert.pem
